// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "joyku/pkg/joycon"
import "fmt"

func getJoyconColor(jc *joycon.Joycon) templ.SafeCSS {
	var r, g, b, a uint32
	if jc.BodyColor != nil {
		r, g, b, a = jc.BodyColor.RGBA()
		// Unshift RGBA values
		r >>= 8
		g >>= 8
		b >>= 8
		a >>= 8
	}
	return templ.SafeCSS(fmt.Sprintf("fill: rgba(%d, %d, %d, %d);", r, g, b, a))
}

func RenderJoycon(joycon *joycon.Joycon) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"joycon\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if joycon.IsLeft() {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<svg style=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues(getJoyconColor(joycon))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/components/joycon.templ`, Line: 22, Col: 47}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" id=\"left-joycon\" xmlns=\"http://www.w3.org/2000/svg\" width=\"89\" height=\"275\" viewBox=\"0 0 89 275\"><path stroke=\"#fff\" d=\"M50 .5h34.5v274H50C22.662 274.5.5 252.338.5 225V50C.5 22.662 22.662.5 50 .5Z\"></path> <circle cx=\"42.5\" cy=\"77.5\" r=\"22.5\" fill=\"#D9D9D9\"></circle> <circle cx=\"42.5\" cy=\"129.5\" r=\"7.5\" fill=\"#D9D9D9\"></circle> <circle cx=\"42.5\" cy=\"159.5\" r=\"7.5\" fill=\"#D9D9D9\"></circle> <circle cx=\"27.5\" cy=\"144.5\" r=\"7.5\" fill=\"#D9D9D9\"></circle> <circle cx=\"57.5\" cy=\"144.5\" r=\"7.5\" fill=\"#D9D9D9\"></circle> <path fill=\"#D9D9D9\" d=\"M62.05 14H74.8v5H62.05zM85 14h4v230h-4zM47 185h15v15H47z\"></path> <circle cx=\"54.5\" cy=\"192.5\" r=\"6.5\" fill=\"#515151\"></circle></svg>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if joycon.IsRight() {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<svg style=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues(getJoyconColor(joycon))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/components/joycon.templ`, Line: 33, Col: 47}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" id=\"right-joycon\" xmlns=\"http://www.w3.org/2000/svg\" width=\"89\" height=\"275\" viewBox=\"0 0 89 275\"><path stroke=\"#fff\" d=\"M39 274.5H4.5V.5H39C66.338.5 88.5 22.662 88.5 50v175c0 27.338-22.162 49.5-49.5 49.5Z\"></path> <circle cx=\"43.5\" cy=\"144.5\" r=\"22.5\" fill=\"#D9D9D9\"></circle> <circle cx=\"43.5\" cy=\"62.5\" r=\"7.5\" fill=\"#D9D9D9\"></circle> <circle cx=\"43.5\" cy=\"92.5\" r=\"7.5\" fill=\"#D9D9D9\"></circle> <circle cx=\"28.5\" cy=\"77.5\" r=\"7.5\" fill=\"#D9D9D9\"></circle> <circle cx=\"58.5\" cy=\"77.5\" r=\"7.5\" fill=\"#D9D9D9\"></circle> <path fill=\"#D9D9D9\" d=\"M13 14h15v5H13z\"></path> <path fill=\"#D9D9D9\" d=\"M18 9h5v15h-5z\"></path> <circle cx=\"30.5\" cy=\"192.5\" r=\"7.5\" fill=\"#D9D9D9\"></circle> <circle cx=\"30.5\" cy=\"192.5\" r=\"5.5\" fill=\"#484848\"></circle> <path fill=\"#D9D9D9\" d=\"M0 14h4v230H0z\"></path></svg>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"info\" hx-vals=\"js:{&#39;joycon&#39;: document.querySelector(&#39;p &gt; .serial-number&#39;).textContent}\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if joycon.IsLeft() {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<h3>Left Joycon</h3>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if joycon.IsRight() {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<h3>Right Joycon</h3>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<p>Serial: <span class=\"serial-number\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(joycon.Serial)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/components/joycon.templ`, Line: 53, Col: 66}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</span></p><p>Battery: Unknown</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !joycon.IsConnected() {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<button class=\"btn\" role=\"button\" hx-post=\"/connect\" hx-target=\"closest .joycon\">Connect</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<button class=\"btn\" role=\"button\" hx-post=\"/disconnect\" hx-confirm=\"Are you sure you want to disconnect this Joycon?\" hx-target=\"#joycon-container\" sse-connect=\"/events\">Disconnect</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
